/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicalIsolationRouteImport } from './routes/clinical/isolation'
import { Route as ClinicalMedicationsRouteImport } from './routes/clinical/medications'
import { Route as ClinicalMortalityRouteImport } from './routes/clinical/mortality'
import { Route as ClinicalRecordsRouteImport } from './routes/clinical/records'
import { Route as HusbandryDailyLogsRouteImport } from './routes/husbandry/daily-logs'
import { Route as HusbandryFeedingRouteImport } from './routes/husbandry/feeding'
import { Route as HusbandryMissingRecordsRouteImport } from './routes/husbandry/missing-records'
import { Route as HusbandryRoundsRouteImport } from './routes/husbandry/rounds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalIsolationRoute = ClinicalIsolationRouteImport.update({
  id: '/clinical/isolation',
  path: '/clinical/isolation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalMedicationsRoute = ClinicalMedicationsRouteImport.update({
  id: '/clinical/medications',
  path: '/clinical/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalMortalityRoute = ClinicalMortalityRouteImport.update({
  id: '/clinical/mortality',
  path: '/clinical/mortality',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRecordsRoute = ClinicalRecordsRouteImport.update({
  id: '/clinical/records',
  path: '/clinical/records',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryDailyLogsRoute = HusbandryDailyLogsRouteImport.update({
  id: '/husbandry/daily-logs',
  path: '/husbandry/daily-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryFeedingRoute = HusbandryFeedingRouteImport.update({
  id: '/husbandry/feeding',
  path: '/husbandry/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryMissingRecordsRoute = HusbandryMissingRecordsRouteImport.update({
  id: '/husbandry/missing-records',
  path: '/husbandry/missing-records',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryRoundsRoute = HusbandryRoundsRouteImport.update({
  id: '/husbandry/rounds',
  path: '/husbandry/rounds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
  id:
    | '__root__'
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalIsolationRoute: typeof ClinicalIsolationRoute
  ClinicalMedicationsRoute: typeof ClinicalMedicationsRoute
  ClinicalMortalityRoute: typeof ClinicalMortalityRoute
  ClinicalRecordsRoute: typeof ClinicalRecordsRoute
  HusbandryDailyLogsRoute: typeof HusbandryDailyLogsRoute
  HusbandryFeedingRoute: typeof HusbandryFeedingRoute
  HusbandryMissingRecordsRoute: typeof HusbandryMissingRecordsRoute
  HusbandryRoundsRoute: typeof HusbandryRoundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/isolation': {
      id: '/clinical/isolation'
      path: '/clinical/isolation'
      fullPath: '/clinical/isolation'
      preLoaderRoute: typeof ClinicalIsolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/medications': {
      id: '/clinical/medications'
      path: '/clinical/medications'
      fullPath: '/clinical/medications'
      preLoaderRoute: typeof ClinicalMedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/mortality': {
      id: '/clinical/mortality'
      path: '/clinical/mortality'
      fullPath: '/clinical/mortality'
      preLoaderRoute: typeof ClinicalMortalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/records': {
      id: '/clinical/records'
      path: '/clinical/records'
      fullPath: '/clinical/records'
      preLoaderRoute: typeof ClinicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/daily-logs': {
      id: '/husbandry/daily-logs'
      path: '/husbandry/daily-logs'
      fullPath: '/husbandry/daily-logs'
      preLoaderRoute: typeof HusbandryDailyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/feeding': {
      id: '/husbandry/feeding'
      path: '/husbandry/feeding'
      fullPath: '/husbandry/feeding'
      preLoaderRoute: typeof HusbandryFeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/missing-records': {
      id: '/husbandry/missing-records'
      path: '/husbandry/missing-records'
      fullPath: '/husbandry/missing-records'
      preLoaderRoute: typeof HusbandryMissingRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/rounds': {
      id: '/husbandry/rounds'
      path: '/husbandry/rounds'
      fullPath: '/husbandry/rounds'
      preLoaderRoute: typeof HusbandryRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalIsolationRoute: ClinicalIsolationRoute,
  ClinicalMedicationsRoute: ClinicalMedicationsRoute,
  ClinicalMortalityRoute: ClinicalMortalityRoute,
  ClinicalRecordsRoute: ClinicalRecordsRoute,
  HusbandryDailyLogsRoute: HusbandryDailyLogsRoute,
  HusbandryFeedingRoute: HusbandryFeedingRoute,
  HusbandryMissingRecordsRoute: HusbandryMissingRecordsRoute,
  HusbandryRoundsRoute: HusbandryRoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
