/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicalIsolationRouteImport } from './routes/clinical/isolation'
import { Route as ClinicalMedicationsRouteImport } from './routes/clinical/medications'
import { Route as ClinicalMortalityRouteImport } from './routes/clinical/mortality'
import { Route as ClinicalRecordsRouteImport } from './routes/clinical/records'
import { Route as HusbandryDailyLogsRouteImport } from './routes/husbandry/daily-logs'
import { Route as HusbandryFeedingRouteImport } from './routes/husbandry/feeding'
import { Route as HusbandryMissingRecordsRouteImport } from './routes/husbandry/missing-records'
import { Route as HusbandryRoundsRouteImport } from './routes/husbandry/rounds'
import { Route as LogisticsCalendarRouteImport } from './routes/logistics/calendar'
import { Route as LogisticsEventsRouteImport } from './routes/logistics/events'
import { Route as LogisticsExternalTransfersRouteImport } from './routes/logistics/external-transfers'
import { Route as LogisticsInternalMovementsRouteImport } from './routes/logistics/internal-movements'
import { Route as LogisticsVouchersRouteImport } from './routes/logistics/vouchers'
import { Route as SafetyDrillsRouteImport } from './routes/safety/drills'
import { Route as SafetyFirstAidRouteImport } from './routes/safety/first-aid'
import { Route as SafetyIncidentsRouteImport } from './routes/safety/incidents'
import { Route as SafetyMaintenanceRouteImport } from './routes/safety/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalIsolationRoute = ClinicalIsolationRouteImport.update({
  id: '/clinical/isolation',
  path: '/clinical/isolation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalMedicationsRoute = ClinicalMedicationsRouteImport.update({
  id: '/clinical/medications',
  path: '/clinical/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalMortalityRoute = ClinicalMortalityRouteImport.update({
  id: '/clinical/mortality',
  path: '/clinical/mortality',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRecordsRoute = ClinicalRecordsRouteImport.update({
  id: '/clinical/records',
  path: '/clinical/records',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryDailyLogsRoute = HusbandryDailyLogsRouteImport.update({
  id: '/husbandry/daily-logs',
  path: '/husbandry/daily-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryFeedingRoute = HusbandryFeedingRouteImport.update({
  id: '/husbandry/feeding',
  path: '/husbandry/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryMissingRecordsRoute = HusbandryMissingRecordsRouteImport.update({
  id: '/husbandry/missing-records',
  path: '/husbandry/missing-records',
  getParentRoute: () => rootRouteImport,
} as any)
const HusbandryRoundsRoute = HusbandryRoundsRouteImport.update({
  id: '/husbandry/rounds',
  path: '/husbandry/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsCalendarRoute = LogisticsCalendarRouteImport.update({
  id: '/logistics/calendar',
  path: '/logistics/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsEventsRoute = LogisticsEventsRouteImport.update({
  id: '/logistics/events',
  path: '/logistics/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsExternalTransfersRoute =
  LogisticsExternalTransfersRouteImport.update({
    id: '/logistics/external-transfers',
    path: '/logistics/external-transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticsInternalMovementsRoute =
  LogisticsInternalMovementsRouteImport.update({
    id: '/logistics/internal-movements',
    path: '/logistics/internal-movements',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticsVouchersRoute = LogisticsVouchersRouteImport.update({
  id: '/logistics/vouchers',
  path: '/logistics/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyDrillsRoute = SafetyDrillsRouteImport.update({
  id: '/safety/drills',
  path: '/safety/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyFirstAidRoute = SafetyFirstAidRouteImport.update({
  id: '/safety/first-aid',
  path: '/safety/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyIncidentsRoute = SafetyIncidentsRouteImport.update({
  id: '/safety/incidents',
  path: '/safety/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyMaintenanceRoute = SafetyMaintenanceRouteImport.update({
  id: '/safety/maintenance',
  path: '/safety/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
  '/logistics/calendar': typeof LogisticsCalendarRoute
  '/logistics/events': typeof LogisticsEventsRoute
  '/logistics/external-transfers': typeof LogisticsExternalTransfersRoute
  '/logistics/internal-movements': typeof LogisticsInternalMovementsRoute
  '/logistics/vouchers': typeof LogisticsVouchersRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
  '/logistics/calendar': typeof LogisticsCalendarRoute
  '/logistics/events': typeof LogisticsEventsRoute
  '/logistics/external-transfers': typeof LogisticsExternalTransfersRoute
  '/logistics/internal-movements': typeof LogisticsInternalMovementsRoute
  '/logistics/vouchers': typeof LogisticsVouchersRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical/isolation': typeof ClinicalIsolationRoute
  '/clinical/medications': typeof ClinicalMedicationsRoute
  '/clinical/mortality': typeof ClinicalMortalityRoute
  '/clinical/records': typeof ClinicalRecordsRoute
  '/husbandry/daily-logs': typeof HusbandryDailyLogsRoute
  '/husbandry/feeding': typeof HusbandryFeedingRoute
  '/husbandry/missing-records': typeof HusbandryMissingRecordsRoute
  '/husbandry/rounds': typeof HusbandryRoundsRoute
  '/logistics/calendar': typeof LogisticsCalendarRoute
  '/logistics/events': typeof LogisticsEventsRoute
  '/logistics/external-transfers': typeof LogisticsExternalTransfersRoute
  '/logistics/internal-movements': typeof LogisticsInternalMovementsRoute
  '/logistics/vouchers': typeof LogisticsVouchersRoute
  '/safety/drills': typeof SafetyDrillsRoute
  '/safety/first-aid': typeof SafetyFirstAidRoute
  '/safety/incidents': typeof SafetyIncidentsRoute
  '/safety/maintenance': typeof SafetyMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
    | '/logistics/calendar'
    | '/logistics/events'
    | '/logistics/external-transfers'
    | '/logistics/internal-movements'
    | '/logistics/vouchers'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
    | '/logistics/calendar'
    | '/logistics/events'
    | '/logistics/external-transfers'
    | '/logistics/internal-movements'
    | '/logistics/vouchers'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
  id:
    | '__root__'
    | '/'
    | '/clinical/isolation'
    | '/clinical/medications'
    | '/clinical/mortality'
    | '/clinical/records'
    | '/husbandry/daily-logs'
    | '/husbandry/feeding'
    | '/husbandry/missing-records'
    | '/husbandry/rounds'
    | '/logistics/calendar'
    | '/logistics/events'
    | '/logistics/external-transfers'
    | '/logistics/internal-movements'
    | '/logistics/vouchers'
    | '/safety/drills'
    | '/safety/first-aid'
    | '/safety/incidents'
    | '/safety/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalIsolationRoute: typeof ClinicalIsolationRoute
  ClinicalMedicationsRoute: typeof ClinicalMedicationsRoute
  ClinicalMortalityRoute: typeof ClinicalMortalityRoute
  ClinicalRecordsRoute: typeof ClinicalRecordsRoute
  HusbandryDailyLogsRoute: typeof HusbandryDailyLogsRoute
  HusbandryFeedingRoute: typeof HusbandryFeedingRoute
  HusbandryMissingRecordsRoute: typeof HusbandryMissingRecordsRoute
  HusbandryRoundsRoute: typeof HusbandryRoundsRoute
  LogisticsCalendarRoute: typeof LogisticsCalendarRoute
  LogisticsEventsRoute: typeof LogisticsEventsRoute
  LogisticsExternalTransfersRoute: typeof LogisticsExternalTransfersRoute
  LogisticsInternalMovementsRoute: typeof LogisticsInternalMovementsRoute
  LogisticsVouchersRoute: typeof LogisticsVouchersRoute
  SafetyDrillsRoute: typeof SafetyDrillsRoute
  SafetyFirstAidRoute: typeof SafetyFirstAidRoute
  SafetyIncidentsRoute: typeof SafetyIncidentsRoute
  SafetyMaintenanceRoute: typeof SafetyMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/isolation': {
      id: '/clinical/isolation'
      path: '/clinical/isolation'
      fullPath: '/clinical/isolation'
      preLoaderRoute: typeof ClinicalIsolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/medications': {
      id: '/clinical/medications'
      path: '/clinical/medications'
      fullPath: '/clinical/medications'
      preLoaderRoute: typeof ClinicalMedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/mortality': {
      id: '/clinical/mortality'
      path: '/clinical/mortality'
      fullPath: '/clinical/mortality'
      preLoaderRoute: typeof ClinicalMortalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical/records': {
      id: '/clinical/records'
      path: '/clinical/records'
      fullPath: '/clinical/records'
      preLoaderRoute: typeof ClinicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/daily-logs': {
      id: '/husbandry/daily-logs'
      path: '/husbandry/daily-logs'
      fullPath: '/husbandry/daily-logs'
      preLoaderRoute: typeof HusbandryDailyLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/feeding': {
      id: '/husbandry/feeding'
      path: '/husbandry/feeding'
      fullPath: '/husbandry/feeding'
      preLoaderRoute: typeof HusbandryFeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/missing-records': {
      id: '/husbandry/missing-records'
      path: '/husbandry/missing-records'
      fullPath: '/husbandry/missing-records'
      preLoaderRoute: typeof HusbandryMissingRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/husbandry/rounds': {
      id: '/husbandry/rounds'
      path: '/husbandry/rounds'
      fullPath: '/husbandry/rounds'
      preLoaderRoute: typeof HusbandryRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/calendar': {
      id: '/logistics/calendar'
      path: '/logistics/calendar'
      fullPath: '/logistics/calendar'
      preLoaderRoute: typeof LogisticsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/events': {
      id: '/logistics/events'
      path: '/logistics/events'
      fullPath: '/logistics/events'
      preLoaderRoute: typeof LogisticsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/external-transfers': {
      id: '/logistics/external-transfers'
      path: '/logistics/external-transfers'
      fullPath: '/logistics/external-transfers'
      preLoaderRoute: typeof LogisticsExternalTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/internal-movements': {
      id: '/logistics/internal-movements'
      path: '/logistics/internal-movements'
      fullPath: '/logistics/internal-movements'
      preLoaderRoute: typeof LogisticsInternalMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/vouchers': {
      id: '/logistics/vouchers'
      path: '/logistics/vouchers'
      fullPath: '/logistics/vouchers'
      preLoaderRoute: typeof LogisticsVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/drills': {
      id: '/safety/drills'
      path: '/safety/drills'
      fullPath: '/safety/drills'
      preLoaderRoute: typeof SafetyDrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/first-aid': {
      id: '/safety/first-aid'
      path: '/safety/first-aid'
      fullPath: '/safety/first-aid'
      preLoaderRoute: typeof SafetyFirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/incidents': {
      id: '/safety/incidents'
      path: '/safety/incidents'
      fullPath: '/safety/incidents'
      preLoaderRoute: typeof SafetyIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/maintenance': {
      id: '/safety/maintenance'
      path: '/safety/maintenance'
      fullPath: '/safety/maintenance'
      preLoaderRoute: typeof SafetyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalIsolationRoute: ClinicalIsolationRoute,
  ClinicalMedicationsRoute: ClinicalMedicationsRoute,
  ClinicalMortalityRoute: ClinicalMortalityRoute,
  ClinicalRecordsRoute: ClinicalRecordsRoute,
  HusbandryDailyLogsRoute: HusbandryDailyLogsRoute,
  HusbandryFeedingRoute: HusbandryFeedingRoute,
  HusbandryMissingRecordsRoute: HusbandryMissingRecordsRoute,
  HusbandryRoundsRoute: HusbandryRoundsRoute,
  LogisticsCalendarRoute: LogisticsCalendarRoute,
  LogisticsEventsRoute: LogisticsEventsRoute,
  LogisticsExternalTransfersRoute: LogisticsExternalTransfersRoute,
  LogisticsInternalMovementsRoute: LogisticsInternalMovementsRoute,
  LogisticsVouchersRoute: LogisticsVouchersRoute,
  SafetyDrillsRoute: SafetyDrillsRoute,
  SafetyFirstAidRoute: SafetyFirstAidRoute,
  SafetyIncidentsRoute: SafetyIncidentsRoute,
  SafetyMaintenanceRoute: SafetyMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
